---
title: "MRS_results"
author: "Ella Davyson"
date: "2023-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Generating MRS weights (LASSO)

Looking at the CpGs involved in the score:

```{r, echo = FALSE}
library(data.table)
library(dplyr)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)

weights <- read.table('/Volumes/igmm/GenScotDepression/users/edavyson/Antidep_methylation/MRS/biglasso/big_lasso_450K_selfrep.txt', header = F)
colnames(weights) <- c('CpG', 'Weight')

# discard the intercept 

weights <- weights[-1,]

# distribution of the effect sizes 

summary(weights$Weight)
ggplot(weights, aes(x = Weight)) + geom_histogram() + theme_minimal()

```

Annotating the CpGs: 

```{r}
# annotate the CpGs 
annot <- getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b4.hg19) %>% as.data.frame()

annot_rel <- annot %>% dplyr::select(Name, chr, pos, Relation_to_Island, Islands_Name, UCSC_RefGene_Name, UCSC_RefGene_Accession, UCSC_RefGene_Group)

weights_annot <- merge(weights, annot_rel, by.x = 'CpG', by.y = 'Name')

table(weights_annot$chr)

# order the CpGs by weight 

weights_annot %>% arrange(abs(Weight)) %>% head()
```
## Overlap of the CpGs with the OSCA self-report and OSCA prescription derived sets ? 


```{r}
sr_cpgs <- readr::read_lines('/Volumes/igmm/GenScotDepression/users/edavyson/Antidep_methylation/OSCA_results/GRM_unadjusted_10_standardised/06_10_update/selfrep_ph3_top100_CpGs_26_10.txt')
pd_cpgs <- readr::read_lines('/Volumes/igmm/GenScotDepression/users/edavyson/Antidep_methylation/OSCA_results/GRM_unadjusted_10_standardised/06_10_update/antidep_ph1_top100_CpGs_26_10.txt')

######################################################

#CpG lists -hypergeometric tests between LASSO and OSCA CpGs (top 100)

######################################################
# total number of CpGs #total number of cpgs fed into the lasso model : N = 365, 912

cpg_phyper <- function(cpgs_A, cpgs_B, totalN, cpglab_A, cpglab_B){
  cpg_overlap <- intersect(cpgs_A, cpgs_B)
  
# phyper: phyper(Overlap-1, group2, Total-group2, group1,lower.tail= FALSE)
  hyper_res <- phyper(length(cpg_overlap)-1, length(cpgs_B), totalN-length(cpgs_B),length(cpgs_A), lower.tail = FALSE)
  res <- data.table(list1 = cpglab_A, list2= cpglab_B, N_list1 = length(cpgs_A), N_list2 = length(cpgs_B), Total = totalN, phyper_p = hyper_res)
  return(res)
}

rbind(cpg_phyper(sr_cpgs, weights$CpG, totalN = 365912, 'Self-report', 'LASSO'), cpg_phyper(pd_cpgs, weights$CpG, totalN = 365912, 'Prescription-derived', 'LASSO'))

######################################################

# Venn Diagrams 

######################################################

sr_lasso_cpgs <- list(sr_cpgs, weights$CpG)
names(sr_lasso_cpgs) <- c('SR', 'LASSO')

pd_lasso_cpgs <- list(pd_cpgs, weights$CpG)
names(pd_lasso_cpgs) <- c('PD', 'LASSO')

png(filename = "/Users/ellad/UniversityEdinburgh/PhD/antidep_methylation/Writing/Supplementary Info/supp_plots/top100cpgs_venndir_LASSO.png", width = 8, height = 6, units = "in", res = 300)

venndir(sr_lasso_cpgs, proportional = TRUE, overlap_type="overlap", label_preset="main items", show_items = "item", item_cex = 1)
venndir(pd_lasso_cpgs, proportional = TRUE, overlap_type="overlap", label_preset="main items", show_items = "item", item_cex = 1)

dev.off()



```

## MRS in Generation Scotland 

Generated MRS in GS using the MRS_calc.R script.

```{r}

# Read in the MRS 

GS_MRS <- read.table('/Volumes/igmm/GenScotDepression/users/edavyson/Antidep_methylation/MRS/GS_testing/test_makeMRS/GS_AD_MRS.txt', header = T)

# read in the phenotype 

selfrep_pheno <- read.csv('/Volumes/igmm/GenScotDepression/users/edavyson/Antidep_methylation/antidep_phenotypes/selfreport/selfrep_pheno3_methyl_03_05.csv', header = T)
selfrep_pheno <- selfrep_pheno %>% filter(!is.na(antidep))
print(paste0('Read in the Antidepressant exposure phenotype for ', 'GS', ': Number of cases: ',
             nrow(selfrep_pheno %>% 
                    filter(antidep==1)), 
             ' Number of controls: ',
             nrow(selfrep_pheno%>% 
                    filter(antidep==0))))
selfrep_pheno_MRS <- merge(selfrep_pheno, MRS, by = 'IID')

print('Plotting MRS distributions for AD exposure cases and controls ')
MRS_pheno_dists <- ggplot(selfrep_pheno_MRS, aes(x = AD_MRS, fill = as.factor(antidep))) + 
  geom_histogram(alpha = 0.8) + 
  theme_minimal() + 
  labs(x = 'Methylation Risk Score', y = 'Count', fill = 'Self-reported AD use') +
  ggtitle('Generation Scotland')

MRS_pheno_dists

```

