library(tidyr)
library(dplyr)
# Read in the phenotype files (residualised)
pd_all <- read.table('residualised_antidep_pheno1_clean_appt_nocolnames.pheno')
colnames(pd_all) <- c("FID", "IID", "antidep")
sr_all <- read.table("residualised_selfrep_pheno3_nocolnames.pheno")
colnames(sr_all) <- c("FID", "IID", "antidep")
# Read in the actual phenotypes (0/1) for the counts (check against log file)
pd_raw <- read.csv("antidep_pheno1_clean_appt.csv", header = T)
sr_raw <- read.csv("selfrep_pheno3_methyl_03_05.csv", header = T)
# Read in the covariate and quantitative covariate file 
covs <- read.table("covs_11_07_GRMFID_nocolnames")
colnames(covs) <- c("FID", "IID", "sex_coded", "Batch")
qcovs <- read.table("qcovs_11_07_GRMFID_nocolnames")
colnames(qcovs) <- c("FID", "IID", "age", "Mono", "lymphocytes", "cg05575921")

# Merge with the phenotype file
pd_covs <- left_join(pd_all %>% select(-FID), covs, by = "IID")
sr_covs <- left_join(sr_all %>% select(-FID), covs, by = "IID")
pd_covs_raw <- left_join(pd_raw %>% select(-FID), covs, by = "IID")
sr_covs_raw <- left_join(sr_raw %>% select(-FID), covs, by = "IID")
table(pd_covs_raw$antidep_pheno1, pd_covs_raw$sex_coded, dnn =c( "Antidepressant Exposure", "Sex"))
table(sr_covs_raw$antidep, sr_covs_raw$sex_coded, dnn =c( "Antidepressant Exposure", "Sex"))

# Separate the covariate file into the males and females - OSCA_covariates.R file Females (0) and Male (1)
table(covs$sex_coded, useNA = "always")
female_covs <- covs %>% filter(sex_coded == 0) %>% select(-sex_coded)
male_covs <- covs %>% filter(sex_coded == 1) %>% select(-sex_coded)
pd_female <- pd_covs %>% filter(sex_coded == 0) %>% select(FID, IID, antidep)
pd_male <- pd_covs %>% filter(sex_coded == 1) %>% select(FID, IID, antidep)
sr_female <- sr_covs %>% filter(sex_coded == 0) %>% select(FID, IID, antidep)
sr_male <- sr_covs %>% filter(sex_coded == 1) %>% select(FID, IID, antidep)

outdir <- "/exports/igmm/eddie/GenScotDepression/users/edavyson/antidep_project/revisions/output/MWAS_sex_segregated/"
write.table(female_covs, paste0(outdir, "covs_11_07_GRMFID_female_nocolnames"), row.names =F, col.names = F, quote = F)
write.table(male_covs, paste0(outdir, "covs_11_07_GRMFID_male_nocolnames"), row.names =F, col.names = F, quote = F)
write.table(pd_female, paste0(outdir, "residualised_antidep_pheno1_clean_appt_female_nocolnames.pheno"), row.names =F, col.names = F, quote = F)
write.table(pd_male, paste0(outdir, "residualised_antidep_pheno1_clean_appt_male_nocolnames.pheno"), row.names =F, col.names = F, quote = F)
write.table(sr_female, paste0(outdir, "residualised_selfrep_pheno3_female_nocolnames.pheno"), row.names =F, col.names = F, quote = F)
write.table(sr_male, paste0(outdir, "residualised_selfrep_pheno3_male_nocolnames.pheno"), row.names =F, col.names = F, quote = F)
